---
- name: Extra vars vault
  hosts: localhost
  #no_log: true

  # reference the encrypted variable file
  vars_files:
    - vars/oscreds.yml

  tasks:
    - name: print out encrypted vars
      debug:
        msg: "{{ imscloud }}"
      no_log: true

